defaults:
  - default
  - _self_

histo_dir: IDPerformanceMon/Tracks/SelectedGoodTracks
ylabel: "Track Efficiency"
ylim: [0.52, 1.01]
ratio_ylim: [0.95, 1.09]
rebin: 1
histograms:
  - histname: trackeff_vs_eta
    xlim: [-4, 4]
  - histname: trackeff_vs_pt
    xlim: [0, 20]
    xlabel: "p_{T} [GeV]"
  - histname: trackeff_vs_d0
    xlim: [-5, 5]
  - histname: trackeff_vs_z0
    xlim: [-150, 150]
  - histname: trackeff_vs_R
    xlim: [0, 30]
