defaults:
  - default
  - _self_

histo_dir: IDPerformanceMon/Tracks/SelectedMatchedTracks/Primary
ratio_ylim: [0.75, 1.45]

canvas:
  atlas_label:
    y: 0.8
  other_label:
    y: 0.725
  legend:
    y: 0.55

histograms:
  - histname: "d0resolutionRMS_vs_eta"
    ylim: [2, 300]
    ylabel: "#sigma(d_{0}) [#mum]"
    xlabel: "#eta^{true}"

  - histname: "z0resolutionRMS_vs_eta"
    ylim: [10, 100000]
    ylabel: "#sigma(z_{0}) [#mum]"
    xlabel: "#eta^{true}"
    is_logy: true

  - histname: "z0sinresolutionRMS_vs_eta"
    ylim: [0, 1000]
    ylabel: "#sigma(z_{0}sin#theta) [#mum]"
    xlabel: "#eta^{true}"

  - histname: "qoverptresolutionRMS_vs_eta"
    ylim: [0.008, 5]
    ylabel: "Realtive track p_{T} resolution"
    xlabel: "#eta^{true}"
    is_logy: true

  - histname: "d0resolutionRMS_vs_pt"
    ylim: [0, 400]
    ylabel: "#sigma(d_{0}) [#mum]"
    xlabel: "p_{T}^{true}"

  - histname: "z0resolutionRMS_vs_pt"
    ylim: [0, 2500]
    ylabel: "#sigma(z_{0}) [#mum]"
    xlabel: "p_{T}^{true}"

  - histname: "z0sinresolutionRMS_vs_pt"
    ylim: [0., 500]
    ylabel: "#sigma(z_{0}sin#theta) [#mum]"
    xlabel: "p_{T}^{true}"

  - histname: "qoverptresolutionRMS_vs_pt"
    ylim: [0.008, 0.05]
    ylabel: "Realtive track p_{T} resolution"
    xlabel: "p_{T}^{true}"

