track_names: "d0, z0, qoverp, qoverpt, theta, phi, pt, z0sin"
num_track_names: 8
track_latex_names: "d_{0}, z_{0}, q/p, q/p_{T}, #theta, #phi, p_{T}, z_{0}sin#theta"
use_all_histograms: false

track_dir_name: ""    # or TightPrimary
