# https://hydra.cc/docs/configure_hydra/intro/

# enable color logging
defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

# output directory, generated dynamically on each run
run:
  dir: ${paths.log_dir}/output/${hydra.job.override_dirname}/${now:%Y-%m-%d}_${now:%H-%M-%S}

# output directory for sweep runs
sweep:
  dir: ${paths.log_dir}/output/sweeps
  subdir: ${hydra.job.override_dirname}