# Embedding Model
embedding:
  model_path: /global/homes/x/xju/m3443/usr/xju/ITk/For2023Paper/TrainedModels/v1/graph_construction-MetricLearning-v1.pt
  node_features: [r,    phi,  z, count_1, charge_count_1, loc_eta_1, loc_phi_1, localDir0_1, localDir1_1, localDir2_1, glob_eta_1, glob_phi_1, eta_angle_1, phi_angle_1]
  node_scales: [1000, 3.14, 3000, 2, 12, 1, 3.14, 1, 1, 1, 1, 3.14, 3, 1]
  r_infer: 0.1
  knn_infer: 1000
  knn_backend: FAISS-CPU-Flatl2

# Filtering Model
filtering:
  model_path: /global/homes/x/xju/m3443/usr/xju/ITk/For2023Paper/TrainedModels/v1/edge_classifier-PermutationInvariantFilter-v1.pt
  node_features: [r,    phi,  z, count_1, charge_count_1, loc_eta_1, loc_phi_1, localDir0_1, localDir1_1, localDir2_1, glob_eta_1, glob_phi_1, eta_angle_1, phi_angle_1, count_2, charge_count_2, loc_eta_2, loc_phi_2, localDir0_2, localDir1_2, localDir2_2, glob_eta_2, glob_phi_2, eta_angle_2, phi_angle_2]
  node_scales:   [1000, 3.14, 3000, 2, 12, 1, 3.14, 1, 1, 1, 1, 3.14, 3, 1, 2, 12, 1, 3.14, 1, 1, 1, 1, 3.14, 3, 1]
  batch_size: 1_000_000

gnn:
  node_features: [r,    phi,  z, count_1, charge_count_1, loc_eta_1, loc_phi_1, localDir0_1, localDir1_1, localDir2_1, glob_eta_1, glob_phi_1, eta_angle_1, phi_angle_1, count_2, charge_count_2, loc_eta_2, loc_phi_2, localDir0_2, localDir1_2, localDir2_2, glob_eta_2, glob_phi_2, eta_angle_2, phi_angle_2]
  node_scales:   [1000, 3.14, 3000, 2, 12, 1, 3.14, 1, 1, 1, 1, 3.14, 3, 1, 2, 12, 1, 3.14, 1, 1, 1, 1, 3.14, 3, 1]
